"""Simple i18n map with multi-language support.
Default language is zhCN. You can override via env `ZFEIQ_LANG` or call
`set_language('enUS'|'zhCN'|'frFR'|'esES')`.
"""

import os

_LANG = os.environ.get('ZFEIQ_LANG', 'zhCN')

SUPPORTED_LANGS = [
    ('zhCN', 'enUS', 'frFR', 'esES'),
    ('简体中文', 'English', 'Français', 'Español')
]

STRINGS = {
    'zhCN': {
        'settings_title': 'ZFeiQ 设置',
        'tab_basic': '基础设置',
        'tab_security': '安全与调试',
        'tab_about': '关于',
        'btn_save': '保存配置',
        'grp_user': '个人与状态',
        'lbl_nickname': '用户昵称',
        'lbl_status': '当前状态',
        'lbl_bound_ip': '绑定 IP',
        'grp_ui': '界面与国际化',
        'lbl_theme': '外观主题',
        'lbl_encoding': '消息编码',
        'lbl_language': '界面语言',
        'grp_file': '文件存储',
        'status_online': '在线',
        'status_busy': '忙碌',
        'status_away': '离开',
        'status_offline': '离线',
        'btn_settings': '⚙ 设置',
        'btn_group': '组管理',
        'group_prefix': '群组: ',
        'lbl_download_dir': '下载目录',
        'lbl_screenshot_dir': '截图目录',
        'theme_light': '浅色',
        'theme_dark': '深色',
        'ready': '就绪',
        'enc_off': '关闭加密 (off)',
        'enc_on': '开启加密 (on)',
        'enc_strict': '严格加密 (strict)',
        'btn_browse': '...',
        'choose_dir': '选择目录',
        'grp_fingerprint': '加密指纹 (X25519)',
        'btn_regen': '⚠️ 重生成密钥对',
        'grp_session_enc': '会话加密',
        'lbl_encrypt_mode': '加密模式',
        'grp_debug': '调试选项',
        'chk_raw': '在控制台显示原始密文 (Raw Crypto Data)',
        'chk_log_debug': '开启详细日志 (Debug Level)',
        'lbl_core_version': '核心版本',
        'lbl_last_update': '最后更新',
        'lbl_system_platform': '系统平台',
        'lbl_runtime': '运行环境',
        'btn_open_repo': '打开源码仓库 (GitHub)',
        'warn_title': '警告',
        'regen_warning': '重生成密钥将导致之前的加密会话失效，且无法解密历史加密消息。\n确定要继续吗？',
        'info_title': '提示',
        'regen_success': '密钥已重置并已广播新指纹',
        'err_title': '错误',
        'regen_fail': '密钥重置失败: {err}',
        'err_nickname_empty': '昵称不能为空',
        'broadcast_hall': '群聊大厅',
        'send_file_prompt': '请选择具体的接收方再发送文件（广播不支持文件发送）',
        'file_unavailable': '文件尚未下载或路径不可用。',
        'encrypted': '已加密',
        'unencrypted': '未加密',
        'enc_reset': '加密已重置，正在重新握手...',
        'btn_emoji': '表情',
        'btn_screen': '截图',
        'btn_quick': '常用语',
        'btn_file': '文件',
        'btn_ocr': '文字识别',
        'send_button': '发送(S)',
        'search_placeholder': '搜索用户 / IP / 组',
        'input_placeholder': '发送消息... (Enter 发送，Shift+Enter 换行)',
        'group_mgr_placeholder': '组管理功能尚未实现（占位）。',
        'emoji_placeholder': '功能开发中：表情选择',
        'screen_placeholder': '功能开发中：屏幕截图',
        'no_quick_texts': '暂无常用语配置 (可在 config/quick_texts.txt 编辑)',
        'ocr_select': '选择图片进行OCR',
        'ocr_in_progress': '正在识别: {name} ...',
        'ocr_no_text': 'OCR 未识别到文字。',
        'ocr_fail': 'OCR 失败: {err}',
        'ocr_success_unknown': 'OCR 识别成功 ({engine})，时间：未知',
        'ocr_success': 'OCR 识别成功 ({engine})，时间： {sec} 秒',
        'detect_launcher_fail': '无法检测到可用的打开器。请确保已安装 xdg-utils 或在系统中为该文件类型设置默认应用。',
        'file_transferring': '文件正在传输中，请稍后打开。',
        'file_waiting': '文件尚未开始下载，等待接收或手动接受。',
        'select_file': '选择文件'
    },
    'enUS': {
        'settings_title': 'ZFeiQ Settings',
        'tab_basic': 'Basic',
        'tab_security': 'Security & Debug',
        'tab_about': 'About',
        'btn_save': 'Save',
        'grp_user': 'Profile & Status',
        'lbl_nickname': 'Nickname',
        'lbl_status': 'Status',
        'lbl_bound_ip': 'Bound IP',
        'grp_ui': 'Appearance & Language',
        'lbl_theme': 'Theme',
        'lbl_encoding': 'Message Encoding',
        'lbl_language': 'Language',
        'grp_file': 'File Storage',
        'lbl_download_dir': 'Download Dir',
        'lbl_screenshot_dir': 'Screenshot Dir',
        'btn_browse': '...',
        'choose_dir': 'Choose Directory',
        'grp_fingerprint': 'Encryption Fingerprint (X25519)',
        'btn_regen': '⚠️ Regenerate Keypair',
        'grp_session_enc': 'Session Encryption',
        'lbl_encrypt_mode': 'Encrypt Mode',
        'grp_debug': 'Debug Options',
        'chk_raw': 'Show raw crypto data in console',
        'chk_log_debug': 'Enable verbose logging',
        'lbl_core_version': 'Core Version',
        'lbl_last_update': 'Last Update',
        'lbl_system_platform': 'System Platform',
        'lbl_runtime': 'Runtime',
        'btn_open_repo': 'Open Source Repo (GitHub)',
        'theme_light': 'Light',
        'theme_dark': 'Dark',
        'ready': 'Ready',
        'enc_off': 'Encryption Off (off)',
        'enc_on': 'Encryption On (on)',
        'enc_strict': 'Encryption Strict (strict)',
        'warn_title': 'Warning',
        'regen_warning': 'Regenerating keys will invalidate existing encrypted sessions and you will not be able to decrypt past messages.\nContinue?',
        'info_title': 'Info',
        'regen_success': 'Keys regenerated and new fingerprint broadcasted',
        'err_title': 'Error',
        'regen_fail': 'Key regeneration failed: {err}',
        'err_nickname_empty': 'Nickname cannot be empty',
        'broadcast_hall': 'Group Hall',
        'status_online': 'Online',
        'status_busy': 'Busy',
        'status_away': 'Away',
        'status_offline': 'Offline',
        'btn_settings': '⚙ Settings',
        'btn_group': 'Group Manager',
        'group_prefix': 'Group: ',
        'send_file_prompt': 'Please choose a specific recipient (broadcast does not support file sending).',
        'file_unavailable': 'File not downloaded or path unavailable.',
        'encrypted': 'Encrypted',
        'unencrypted': 'Unencrypted',
        'enc_reset': 'Encryption reset, re-handshaking...',
        'btn_emoji': 'Emoji',
        'btn_screen': 'Screenshot',
        'btn_quick': 'Quick Texts',
        'btn_file': 'File',
        'btn_ocr': 'OCR',
        'send_button': 'Send (S)',
        'search_placeholder': 'Search users / IP / groups',
        'input_placeholder': 'Type a message... (Enter to send, Shift+Enter for newline)',
        'group_mgr_placeholder': 'Group manager not implemented (placeholder).',
        'emoji_placeholder': 'Feature in development: Emoji selector',
        'screen_placeholder': 'Feature in development: Screenshot',
        'no_quick_texts': 'No quick texts configured (edit config/quick_texts.txt)',
        'ocr_select': 'Select image for OCR',
        'ocr_in_progress': 'Recognizing: {name} ...',
        'ocr_no_text': 'OCR found no text.',
        'ocr_fail': 'OCR failed: {err}',
        'ocr_success_unknown': 'OCR success ({engine}), time: Unknown',
        'ocr_success': 'OCR success ({engine}), time: {sec} s',
        'detect_launcher_fail': 'No launcher detected. Install xdg-utils or set a default app for this file type.',
        'file_transferring': 'File is transferring, please open later.',
        'file_waiting': 'File not started yet, waiting to receive or accept.',
        'select_file': 'Select File'
    },
    'frFR': {
        'settings_title': 'Paramètres ZFeiQ',
        'tab_basic': 'Basique',
        'tab_security': 'Sécurité & Débogage',
        'tab_about': 'À propos',
        'btn_save': '保存',
        'grp_user': 'Profil & Statut',
        'lbl_nickname': 'Pseudo',
        'lbl_status': 'Statut',
        'lbl_bound_ip': 'IP liée',
        'grp_ui': 'Apparence & Langue',
        'lbl_theme': 'Thème',
        'lbl_encoding': 'Encodage',
        'lbl_language': 'Langue',
        'grp_file': 'Stockage de fichiers',
        'lbl_download_dir': 'Dossier de téléchargement',
        'lbl_screenshot_dir': 'Dossier captures',
        'btn_browse': '...',
        'choose_dir': 'Choisir un répertoire',
        'grp_fingerprint': 'Empreinte (X25519)',
        'btn_regen': '⚠️ Régénérer la paire de clés',
        'grp_session_enc': 'Chiffrement de session',
        'lbl_encrypt_mode': 'Mode chiffrement',
        'grp_debug': 'Options de débogage',
        'chk_raw': 'Afficher les données chiffrées brutes dans la console',
        'chk_log_debug': 'Activer les logs détaillés',
        'lbl_core_version': 'Version du noyau',
        'lbl_last_update': 'Dernière mise à jour',
        'lbl_system_platform': 'Plateforme système',
        'lbl_runtime': 'Environnement',
        'btn_open_repo': 'Ouvrir le dépôt source (GitHub)',
        'theme_light': 'Clair',
        'theme_dark': 'Sombre',
        'ready': 'Prêt',
        'enc_off': 'Chiffrement désactivé (off)',
        'enc_on': 'Chiffrement activé (on)',
        'enc_strict': 'Chiffrement strict (strict)',
        'warn_title': 'Attention',
        'regen_warning': "La régénération des clés invalidera les sessions chiffrées existantes et vous ne pourrez pas déchiffrer les anciens messages.\nContinuer?",
        'info_title': 'Info',
        'regen_success': 'Clés régénérées et nouvelle empreinte diffusée',
        'err_title': 'Erreur',
        'regen_fail': 'Échec de la régénération des clés: {err}',
        'err_nickname_empty': 'Le pseudo ne peut pas être vide',
        'broadcast_hall': 'Hall de groupe',
        'status_online': 'En ligne',
        'status_busy': 'Occupé',
        'status_away': 'Absent',
        'status_offline': 'Hors ligne',
        'btn_settings': '⚙ Paramètres',
        'btn_group': 'Gestion de groupe',
        'group_prefix': 'Groupe : ',
        'send_file_prompt': "Veuillez choisir un destinataire spécifique (la diffusion n'autorise pas l'envoi de fichiers).",
        'file_unavailable': 'Fichier non téléchargé ou chemin indisponible.',
        'encrypted': 'Chiffré',
        'unencrypted': 'Non chiffré',
        'enc_reset': 'Chiffrement réinitialisé, nouvelle négociation...',
        'btn_emoji': 'Émoji',
        'btn_screen': 'Capture',
        'btn_quick': 'Phrases',
        'btn_file': 'Fichier',
        'btn_ocr': 'OCR',
        'send_button': 'Envoyer (S)',
        'search_placeholder': 'Rechercher utilisateurs / IP / groupes',
        'input_placeholder': 'Écrire un message... (Entrée pour envoyer, Maj+Entrée pour ligne)',
        'group_mgr_placeholder': "Gestion de groupe non implémentée (bouchon).",
        'emoji_placeholder': 'Fonction en cours : Sélecteur émoji',
        'screen_placeholder': 'Fonction en cours : Capture écran',
        'no_quick_texts': 'Aucune phrase définie (éditer config/quick_texts.txt)',
        'ocr_select': "Sélectionner une image pour l'OCR",
        'ocr_in_progress': 'Reconnaissance: {name} ...',
        'ocr_no_text': "OCR n'a trouvé aucun texte.",
        'ocr_fail': "Échec OCR: {err}",
        'ocr_success_unknown': "Succès OCR ({engine}), temps : Inconnu",
        'ocr_success': 'Succès OCR ({engine}), temps : {sec} s',
        'detect_launcher_fail': "Aucun lanceur détecté. Installez xdg-utils ou définissez une application par défaut pour ce type de fichier.",
        'file_transferring': 'Le fichier est en cours de transfert, ouvrez-le plus tard.',
        'file_waiting': "Le fichier n'a pas encore démarré, en attente de réception ou d'acceptation.",
        'select_file': 'Sélectionner un fichier'
    },
    'esES': {
        'settings_title': 'Ajustes ZFeiQ',
        'tab_basic': 'Básico',
        'tab_security': 'Seguridad y Depuración',
        'tab_about': 'Acerca de',
        'btn_save': 'Guardar',
        'grp_user': 'Perfil y Estado',
        'lbl_nickname': 'Apodo',
        'lbl_status': 'Estado',
        'lbl_bound_ip': 'IP vinculada',
        'grp_ui': 'Apariencia e Idioma',
        'lbl_theme': 'Tema',
        'lbl_encoding': 'Codificación',
        'lbl_language': 'Idioma',
        'grp_file': 'Almacenamiento de archivos',
        'lbl_download_dir': 'Directorio de descargas',
        'lbl_screenshot_dir': 'Directorio de capturas',
        'btn_browse': '...',
        'choose_dir': 'Elegir carpeta',
        'grp_fingerprint': 'Huella (X25519)',
        'btn_regen': '⚠️ Regenerar par de claves',
        'grp_session_enc': 'Cifrado de sesión',
        'lbl_encrypt_mode': 'Modo de cifrado',
        'grp_debug': 'Opciones de depuración',
        'chk_raw': 'Mostrar datos crudos de cifrado en la consola',
        'chk_log_debug': 'Habilitar registro detallado',
        'lbl_core_version': 'Versión del núcleo',
        'lbl_last_update': 'Última actualización',
        'lbl_system_platform': 'Plataforma del sistema',
        'lbl_runtime': 'Entorno de ejecución',
        'btn_open_repo': 'Abrir repositorio (GitHub)',
        'theme_light': 'Claro',
        'theme_dark': 'Oscuro',
        'ready': 'Listo',
        'enc_off': 'Cifrado Desactivado (off)',
        'enc_on': 'Cifrado Activado (on)',
        'enc_strict': 'Cifrado Estricto (strict)',
        'warn_title': 'Advertencia',
        'regen_warning': 'Regenerar claves invalidará las sesiones cifradas existentes y no podrá descifrar mensajes anteriores.\n¿Continuar?',
        'info_title': 'Información',
        'regen_success': 'Claves regeneradas y nueva huella difundida',
        'err_title': 'Error',
        'regen_fail': 'Fallo al regenerar claves: {err}',
        'err_nickname_empty': 'El apodo no puede estar vacío',
        'broadcast_hall': 'Sala de grupo',
        'status_online': 'En línea',
        'status_busy': 'Ocupado',
        'status_away': 'Ausente',
        'status_offline': 'Desconectado',
        'btn_settings': '⚙ Ajustes',
        'btn_group': 'Gestor de grupos',
        'group_prefix': 'Grupo: ',
        'send_file_prompt': 'Elija un destinatario específico (la difusión no admite envío de archivos).',
        'file_unavailable': 'Archivo no descargado o ruta no disponible.',
        'encrypted': 'Cifrado',
        'unencrypted': 'No cifrado',
        'enc_reset': 'Cifrado reiniciado, rehaciendo el handshake...',
        'btn_emoji': 'Emoji',
        'btn_screen': 'Captura',
        'btn_quick': 'Frases',
        'btn_file': 'Archivo',
        'btn_ocr': 'OCR',
        'send_button': 'Enviar (S)',
        'search_placeholder': 'Buscar usuarios / IP / grupos',
        'input_placeholder': 'Escribe un mensaje... (Enter para enviar, Shift+Enter nueva línea)',
        'group_mgr_placeholder': 'Gestor de grupos no implementado (placeholder).',
        'emoji_placeholder': 'Función en desarrollo: Selector de emojis',
        'screen_placeholder': 'Función en desarrollo: Captura de pantalla',
        'no_quick_texts': 'No hay frases configuradas (editar config/quick_texts.txt)',
        'ocr_select': 'Seleccionar imagen para OCR',
        'ocr_in_progress': 'Reconociendo: {name} ...',
        'ocr_no_text': 'OCR no encontró texto.',
        'ocr_fail': 'OCR falló: {err}',
        'ocr_success_unknown': 'OCR correcto ({engine}), tiempo: Desconocido',
        'ocr_success': 'OCR correcto ({engine}), tiempo: {sec} s',
        'detect_launcher_fail': 'No se detectó lanzador. Instale xdg-utils o establezca una aplicación predeterminada para este tipo de archivo.',
        'file_transferring': 'El archivo se está transfiriendo, ábrelo más tarde.',
        'file_waiting': 'El archivo aún no ha comenzado, esperando recibir o aceptar.',
        'select_file': 'Seleccionar archivo'
    }
}


def set_language(lang: str):
    """Set current language code: 'zhCN'|'enUS'|'frFR'|'esES'"""
    global _LANG
    if lang in STRINGS:
        _LANG = lang


def L(key: str, default: str = '') -> str:
    d = STRINGS.get(_LANG) or STRINGS['zhCN']
    return (d.get(key) or STRINGS['zhCN'].get(key) or default or key)
