# 统一语言模块，集中管理所有界面文本

"""语言与翻译中心。

提供统一的翻译访问与语言切换支持，使用方式：

    from zfeiq_gui.lang import t, set_language
    label.setText(t['login_welcome'])  # t 是当前语言的翻译包(dict-like)

页面中所有文本统一使用 t['key'] 访问，禁止再使用 t.get(...)。
若键缺失将返回 "??key??" 以便在开发阶段快速发现。
支持从状态文件加载上次使用的语言，并可在运行时切换。
"""

import json
import os
from typing import Dict

LANG_MAP: Dict[str, Dict[str, str]] = {
    'zhCN': {
        'accept': '接收',
        'all_display': '所有在线',
        'all_tab': '全部',
        'apply': '应用',
        'avatar': '头像',
        'avatar_placeholder': '头像文件（PNG/JPG，可选）',
        'broadcast_label': '广播：{bcast}',
        'bind_ip': '绑定IP',
        'browse': '浏览…',
        'browse_ss': '浏览截图…',
        'browse_dialog_title': '选择要发送的文件',
        'browse_ss': '浏览截图…',
        'busy': '忙碌',
        'cancel': '放弃',
        'chat': '聊天',
        'chat_placeholder': '消息接收区：显示聊天记录及文件提示',
        'chat_target_unselected': '聊天对象：未选择',
        'debug': '调试日志',
        'discover': '发现',
        'discover_ph': 'ipv4，可留空广播',
        'discover_tip': '在指定 IP 或广播发现在线用户（留空则广播）',
        'download_dir': '下载目录',
        'encoding': '编码',
        'encoding_selftest': '编码自检',
        'encoding_selftest_sample': '编码自检：中文✓ English✓ Emoji😀 αßé',
        'enc_mode': '加密模式',
        'enc_test': '编码自检',
        'emoji': '表情',
        'emoji_dialog_title': '表情',
        'emoji_tab_custom': '自定义',
        'emoji_tab_standard': 'Emoji',
        'emotes': '表情',
        'emotes_add': '添加表情',
        'emotes_back': '返回聊天',
        'emotes_pick_dir': '选择目录',
        'emotes_send': '发送选中',
        'expire': '过期时长（秒）',
        'files': '文件',
        'files_tab': '文件',
        'file_done_label': '文件完成',
        'file_offer_label': '文件要约',
        'file_progress_label': '文件进度',
        'file_sent_prefix': '已发送文件: ',
        'general_tab': '通用',
        'groups': '组',
        'groups_tab': '组',
        'group_enter': '进入聊天',
        'group_label_prefix': '群组：',
        'group_new': '新建分组',
        'group_new_name': '新名称：',
        'group_rename': '重命名',
        'group_search_ph': '搜索组名/成员…',
        'group_send': '群发',
        'help': '帮助',
        'history': '历史',
        'history_header': '历史：',
        'history_close': '关闭',
        'history_empty': '(无记录)',
        'history_title': '历史记录',
        'history_no_target': '请选择一个聊天对象后再查看历史。',
        'iface': '网卡IP',
        'images_filter': 'Images (*.png *.jpg *.jpeg)',
        'info': '信息',
        'ip': 'IP',
        'ip_label_prefix': 'IP',
        'keepalive': '保活时间（秒）',
        'key_export': '导出公钥…',
        'key_fp': '指纹：-',
        'key_refresh': '刷新指纹',
        'key_regen': '重生成密钥',
        'key_section': '安全与密钥',
        'lang': '语言',
        'local_label': '本机：{local} / {prefix}',
        'login': '登录',
        'login_help_text': (
            '1) 输入用户名并选择 IP\n'
            '2) 登录后在用户/组页面选择聊天对象\n'
            '3) 聊天：Enter 发送，Shift+Enter 换行；Ctrl+V 可粘贴文件加入待发送。\n'
            "   表情：点击‘表情’打开对话框，含 Emoji 与自定义表情。\n"
            '   截图：支持框选区域，按 ESC 取消。\n'
            '4) 设置：语言/状态/编码/主题、下载与截图目录、头像；编码自检位于 设置-通用。\n'
        ),
        'login_welcome': '欢迎使用 ZFeiQ，请先登录',
        'logout': '注销',
        'logout_long': '登出',
        'mask_label': '掩码：{mask}',
        'member_add': '添加成员',
        'member_del': '移除成员',
        'member_ph': '添加/移除成员…',
        'me_label': '我',
        'network_tab': '网络',
        'nodes_label': '在线节点: {count}',
        'no_target_warning_body': '请先在用户或组页面选择聊天对象。',
        'no_target_warning_title': '未选择目标',
        'online': '在线',
        'away': '离开',
        'online_nodes': '在线节点',
        'outbox_placeholder': '输入消息，Enter 发送，Shift+Enter 换行',
        'personal_tab': '个人',
        'pick_avatar': '选择头像…',
        'pick_avatar_dialog': '选择头像图片',
        'pick_download_dir': '选择下载目录',
        'pick_ip': '选择IP',
        'pick_screenshot_dir': '选择截图保存目录',
        'pickdir': '选择保存目录',
        'platform': '当前平台',
        'preview': '预览',
        'quick': '常用语',
        'refresh': '刷新',
        'custom_emotes_unavailable': '自定义表情不可用',
        'screenshot': '截图',
        'setdefault': '设为默认',
                'search': 'Search',
                'clear': 'Clear',
        'screenshot_dir': '截图目录',
        'saved_to': '保存到',
        'search_ph': '搜索用户名或IP…',
        'send': '发送',
        'sendfile': '发送文件',
        'settings': '设置',
        'status': '状态',
        'status_prefix': '状态：',
        'subnet_mask': '子网掩码',
        'theme': '主题',
        'trace': '诊断日志',
        'users': '用户',
        'users_tab': '用户',
        'username': '用户名',
        'username_ph': '输入用户名…',
        'version': '版本',
    },
    'enUS': {
        'accept': 'Accept',
        'all_display': 'All online',
        'all_tab': 'All',
        'apply': 'Apply',
        'avatar': 'Avatar',
        'avatar_placeholder': 'Avatar file (PNG/JPG, optional)',
        'broadcast_label': 'Broadcast: {bcast}',
        'bind_ip': 'Bind IP',
        'browse': 'Browse…',
        'browse_ss': 'Browse Screenshot…',
        'browse_dialog_title': 'Pick files to send',
        'browse_ss': 'Browse Screenshot…',
        'busy': 'Busy',
        'cancel': 'Decline',
        'chat': 'Chat',
        'chat_placeholder': 'Chat area: shows messages and file tips',
        'chat_target_unselected': 'Chat target not selected',
        'debug': 'Debug Log',
        'discover': 'Discover',
        'discover_ph': 'ipv4, leave blank for broadcast',
        'discover_tip': 'Discover online users by IP or broadcast (leave blank for broadcast)',
        'download_dir': 'Download Dir',
        'encoding': 'Encoding',
        'encoding_selftest': 'Encoding Self-Test',
        'encoding_selftest_sample': 'Encoding self-test: 中文✓ English✓ Emoji😀 αßé',
        'enc_mode': 'Encryption Mode',
        'enc_test': 'Encoding Self-Test',
        'emoji': 'Emotes',
        'emoji_dialog_title': 'Emotes',
        'emoji_tab_custom': 'Custom',
        'emoji_tab_standard': 'Emoji',
        'emotes': 'Emotes',
        'emotes_add': 'Add Emote',
        'emotes_back': 'Back to chat',
        'emotes_pick_dir': 'Pick directory',
        'emotes_send': 'Send selected',
        'expire': 'Expire (s)',
        'files': 'Files',
        'files_tab': 'Files',
        'file_done_label': 'File Complete',
        'file_offer_label': 'File Offer',
        'file_progress_label': 'File Progress',
        'file_sent_prefix': 'File Sent: ',
        'general_tab': 'General',
        'groups': 'Groups',
        'groups_tab': 'Groups',
        'group_enter': 'Enter Chat',
        'group_label_prefix': 'Group: ',
        'group_new': 'New Group',
        'group_new_name': 'New name:',
        'group_rename': 'Rename',
        'group_search_ph': 'Search group/member…',
        'group_send': 'Group Send',
        'help': 'Help',
        'history': 'History',
        'history_header': 'History: ',
        'history_close': 'Close',
        'history_empty': '(no records)',
        'history_title': 'History',
        'history_no_target': 'Select a chat target before viewing history.',
        'iface': 'Interface IP',
        'images_filter': 'Images (*.png *.jpg *.jpeg)',
        'info': 'Info',
        'ip': 'IP',
        'ip_label_prefix': 'IP',
        'keepalive': 'Keepalive (s)',
        'key_export': 'Export public key…',
        'key_fp': 'Fingerprint: -',
        'key_refresh': 'Refresh fingerprint',
        'key_regen': 'Regenerate keys',
        'key_section': 'Security & Keys',
        'lang': 'Language',
        'local_label': 'Local: {local} / {prefix}',
        'login': 'Login',
        'login_help_text': (
            '1) Enter username and select IP\n'
            '2) After login choose chat targets on Users/Groups tabs\n'
            '3) Chat: Enter to send, Shift+Enter for newline; Ctrl+V attaches files.\n'
            "   Emotes: click \"Emotes\" for Emoji & custom images.\n"
            '   Screenshot: drag to capture area, ESC to cancel.\n'
            '4) Settings: language/status/encoding/theme, download and screenshot dirs, avatar; encoding self-test lives in Settings-General.\n'
        ),
        'login_welcome': 'Welcome to ZFeiQ, please login first',
        'logout': 'Logout',
        'logout_long': 'Logout',
        'mask_label': 'Mask: {mask}',
        'member_add': 'Add Member',
        'member_del': 'Remove Member',
        'member_ph': 'Add/Remove member…',
        'me_label': 'Me',
        'network_tab': 'Network',
        'nodes_label': 'Online nodes: {count}',
        'no_target_warning_body': 'Pick a user or group before sending.',
        'no_target_warning_title': 'No target selected',
        'online': 'Online',
        'away': 'Away',
        'online_nodes': 'Online nodes',
        'outbox_placeholder': 'Enter message, press Enter to send, Shift+Enter for newline',
        'personal_tab': 'Personal',
        'pick_avatar': 'Pick Avatar…',
        'pick_avatar_dialog': 'Pick Avatar Image',
        'pick_download_dir': 'Pick Download Directory',
        'pick_ip': 'Pick IP',
        'pick_screenshot_dir': 'Pick Screenshot Directory',
        'pickdir': 'Pick Save Dir',
        'platform': 'Platform',
        'preview': 'Preview',
        'quick': 'Snippets',
        'refresh': 'Refresh',
        'screenshot': 'Screenshot',
        'screenshot_dir': 'Screenshot Dir',
        'saved_to': 'saved to',
        'search_ph': 'Search user or IP…',
        'send': 'Send',
        'sendfile': 'Send File',
        'settings': 'Settings',
        'status': 'Status',
        'status_prefix': 'Status: ',
        'subnet_mask': 'Subnet Mask',
        'theme': 'Theme',
        'trace': 'Trace Log',
        'users': 'Users',
        'users_tab': 'Users',
        'username': 'Username',
        'username_ph': 'Enter username…',
        'version': 'Version',
        # CLI-specific keys (used by CLI adapter)
        'set_language_usage': 'Usage: set language <lang>',
        'set_language_success': 'Language set: ',
        'set_language_module_na': 'Translation module not available',
        'set_language_failed': 'Language switch failed: ',
        'msg_incoming': '[IN] ',
        'msg_sent': '[SENT] ',
        'file_offer_cli': '[FILE OFFER #',
        'file_progress_cli': '[FILE PROGRESS] ',
        'file_complete_error': '[FILE COMPLETE] error: ',
        'file_complete_saved': '[FILE COMPLETE] saved ',
        'net_rebind': '[NET] rebind -> ',
        'discover_sent': '[DISCOVER] broadcast sent',
        'discover_failed': '[DISCOVER] failed: ',
        'send_error': '[SEND] error: ',
        'group_members': '[GROUP] ',
        'group_no_members': '[GROUP] no members for ',
        'file_path_not_found': '[FILE] path not found',
        'file_register_failed': '[FILE] register failed: ',
        'file_offer_sent': '[FILE] offer sent to ',
        'file_pending_offers': 'Pending file offers',
        'file_unknown_offer': 'Unknown offer id',
        'file_accepting_offer': 'Accepting offer ',
        'file_missing_remote_ip': '[FILE] missing remote_ip',
        'file_download_started': '[FILE] download started -> ',
        'file_download_failed': '[FILE] download failed: ',
        'file_cancel': '[FILE] cancel ',
        'file_mapping_unregistered': '[FILE] mapping unregistered',
        'set_create_dir_failed': 'Create directory failed: ',
        'set_download_dir': 'Download dir = ',
        'set_persist_failed': 'Persist failed: ',
        'set_status': 'Status -> ',
        'set_keepalive': 'Keepalive = ',
        'set_keepalive_failed': 'Keepalive failed: ',
        'set_expire': 'Expire = ',
        'set_expire_failed': 'Expire failed: ',
        'set_bind': 'Bind IP',
        'set_bind_unlocked': 'Bind unlocked; auto-rebind allowed',
        'logout_done': 'Logout done',
        'download_exists': 'download exists:',
        'cli_running_as': 'ZFeiQ CLI adapter running as ',
        'usage_send': 'usage: send <target> <text>',
        'usage_group': 'group usage: group <name> -add <user> | -send <text>',
        'usage_file': 'file usage: file send <target> <path> | file list | file accept <id> [ip] [dest]',
        'usage_set': 'set usage: set download_dir <path> | set status <token> | set bind <ip>',
        'info_net': '[INFO NET]',
        'info_net_item': '  ',
        'info_net_fallback': '[INFO] bind_ip=',
        'history_last_10': '[HISTORY LAST 10]',
        'usage_search': 'search usage: search user:<name>|ip:<addr>|group:<name>',
        'search_user_results': '[SEARCH user=',
        'search_ip_results': '[SEARCH ip=',
        'search_type_not_supported': 'search type not supported',
        'search_not_implemented': 'search not implemented in adapter',
        'unknown_command': 'unknown command ',
        'command_error': 'command error: ',
        # CLI-specific keys (used by CLI adapter)
        'set_language_usage': '用法: set language <lang>',
        'set_language_success': '语言已切换: ',
        'set_language_module_na': '翻译模块不可用，无法切换语言',
        'set_language_failed': '语言切换失败: ',
        'msg_incoming': '[收信] ',
        'msg_sent': '[已发] ',
        'file_offer_cli': '[文件要约 #',
        'file_progress_cli': '[文件进度] ',
        'file_complete_error': '[文件] 完成(错误): ',
        'file_complete_saved': '[文件] 保存 ',
        'net_rebind': '[网络] 重新绑定 -> ',
        'discover_sent': '[发现] 已广播',
        'discover_failed': '[发现] 失败: ',
        'send_error': '[发送] 错误: ',
        'group_members': '[组] ',
        'group_no_members': '[组] 无成员: ',
        'file_path_not_found': '[文件] 路径未找到',
        'file_register_failed': '[文件] 注册失败: ',
        'file_offer_sent': '[文件] 要约已发送: ',
        'file_pending_offers': '待处理要约',
        'file_unknown_offer': '未知的要约 id',
        'file_accepting_offer': '接受要约 ',
        'file_missing_remote_ip': '[文件] 缺少远程 IP',
        'file_download_started': '[文件] 开始下载 -> ',
        'file_download_failed': '[文件] 下载失败: ',
        'file_cancel': '[文件] 取消 ',
        'file_mapping_unregistered': '[文件] 映射已注销',
        'set_create_dir_failed': '创建目录失败: ',
        'set_download_dir': '下载目录 = ',
        'set_persist_failed': '写入配置失败: ',
        'set_status': '状态 -> ',
        'set_keepalive': '保活 = ',
        'set_keepalive_failed': '保活设置失败: ',
        'set_expire': '过期 = ',
        'set_expire_failed': '过期设置失败: ',
        'set_bind': '绑定 IP',
        'set_bind_unlocked': '已解锁绑定；允许自动切换网卡',
        'logout_done': '注销完成',
        'download_exists': 'download exists:',
        'cli_running_as': 'ZFeiQ CLI 以用户运行: ',
        'usage_send': '用法: send <target> <text>',
        'usage_group': '组用法: group <name> -add <user> | -send <text>',
        'usage_file': 'file 用法: file send <target> <path> | file list | file accept <id> [ip] [dest]',
        'usage_set': 'set 用法: set download_dir <path> | set status <token> | set bind <ip>',
        'info_net': '[网络信息]',
        'info_net_item': '  ',
        'info_net_fallback': '[INFO] bind_ip=',
        'history_last_10': '[最近 10 条历史]',
        'usage_search': 'search 用法: search user:<name>|ip:<addr>|group:<name>',
        'search_user_results': '[SEARCH user=',
        'search_ip_results': '[SEARCH ip=',
        'search_type_not_supported': 'search 类型暂不支持',
        'search_not_implemented': 'search 功能未实现',
        'unknown_command': '未知命令 ',
        'command_error': '命令错误: ',
        'custom_emotes_unavailable': 'Custom emotes unavailable',
        'setdefault': 'Set Default',
    }
}

_current_lang_key: str = 'zhCN'

class _TranslationProxy(dict):
    """dict 子类：缺失键返回占位符，便于统一 t['key'] 调用。
    不鼓励直接实例化，使用 module-level 全局 t。
    """
    def __getitem__(self, key: str) -> str:  # type: ignore[override]
        base = LANG_MAP.get(_current_lang_key, LANG_MAP['zhCN'])
        if key in base:
            return base[key]
        # 缺失键：返回占位符，方便调试
        return f'??{key}??'

    # 禁止使用 get，强迫统一风格；如被旧代码调用则仍给出值 + 警告占位
    def get(self, key: str, default=None):  # type: ignore[override]
        return self.__getitem__(key)

def _load_initial_language(state_path: str = 'zfeiq_state.json', default: str = 'zhCN') -> str:
    """从状态文件读取 language 字段，失败则使用默认。"""
    try:
        if os.path.exists(state_path):
            with open(state_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
            lang = data.get('config', {}).get('language')
            if isinstance(lang, str) and lang in LANG_MAP:
                return lang
    except Exception:
        pass
    return default

def set_language(lang: str) -> None:
    """切换当前语言。若 lang 不存在则忽略。"""
    global _current_lang_key
    if lang in LANG_MAP:
        _current_lang_key = lang

def get_current_language() -> str:
    return _current_lang_key

def get_translations(lang: str) -> dict:  # 兼容旧代码，未来可移除
    return LANG_MAP.get(lang, LANG_MAP['zhCN'])

# 初始化全局 t
_current_lang_key = _load_initial_language()
t = _TranslationProxy()  # t 是当前语言翻译包

__all__ = ['t', 'set_language', 'get_current_language', 'get_translations', 'LANG_MAP']
